### ISSUE TITLE
Clarify in the README how the container should be used in your application

### ISSUE THREAD

**Issue by timrogers** [mlibrary/closet#1]
The readme states:

> [I]t would be a mistake to write all of your classes such that they except a single parameter called container.

I'd love to understand more, from your perspective, why that would be a mistake and what the alternative is.

**Comment by malakai97** [comment]
Hi, thanks for the interest.  

[Blair Anderson](https://github.com/blairanderson) said it better than I can in  [this excellent article](https://gist.github.com/malakai97/b1d3bdf6d80c6f99a875930981243f9d), which is linked in the readme.  The short version is this:

The domain of your application is not concerned with the design patterns you use to implement it; therefore, the domain entities within in it should represent the domain, not the patterns.

So the mistake is having `Car.new(container)` when what you want is `Car.new(make, model, year)`.

**Comment by malakai97** [comment]
On a second reading, I think you may be right, and that the linked article does not provide enough insight. This still ends up being a principle of SOLID, so I will look for an appropriate and readily available piece of literature to point to in the readme.
